### ISSUE TITLE
Update readme to make it easier to read

### ISSUE THREAD

**Issue by jatin69** [blockspacer/CXXCTP#75]
**Is your feature request related to a problem? Please describe.**
I went through the readme several times. The sections do not flow. Filled with commands and code, everything looks messy.

**Describe the solution you'd like**
A reorganization of the readme. Complete flow of reading. For eg - 
- What is this project
- What does this do
- Motivation
- How can you use it
    - Example snippets for use
- How can you develop for it
    - Pre requisites
    - configurations
    - build
    - tests

**Describe alternatives you've considered**
I understand this might seem like a low priority task, but a good readme is extremely important. Maybe open this up as a `good-first-issue` so someone else could take it.

**Comment by ezrahayhurst** [comment]
I'd like to have a go at this, I agree that the current order of the readme doesn't flow well.

**Comment by blockspacer** [comment]
@annahayhurst Thanks!
